import type { LStr } from '@/lib/i18n';
import type { Cia, Concept, Control, ControlType, Theme } from '../types';

export const THEMES: { key: Theme; label: LStr; range: string }[] = [
  { key: 'organisational', label: { en: 'Organisational', th: 'องค์กร' }, range: '5.1–5.37' },
  { key: 'people', label: { en: 'People', th: 'บุคลากร' }, range: '6.1–6.8' },
  { key: 'physical', label: { en: 'Physical', th: 'กายภาพ' }, range: '7.1–7.14' },
  { key: 'technological', label: { en: 'Technological', th: 'เทคโนโลยี' }, range: '8.1–8.34' },
];

// [id, title en, title th, summary en, summary th, types, cia, concepts, domains]
type Row = [string, string, string, string, string, string, string, string, string];

const P = 'preventive', D = 'detective', C = 'corrective';

const rows: Row[] = [
  // ── 5 Organisational ────────────────────────────────────────
  ['5.1', 'Policies for information security', 'นโยบายความมั่นคงปลอดภัยสารสนเทศ',
    'Write the top-level security policy and its topic policies, get management to approve them, publish them, and review them on a schedule and after major change.',
    'จัดทำนโยบายความมั่นคงปลอดภัยระดับสูงสุดและนโยบายเฉพาะเรื่อง ให้ผู้บริหารอนุมัติ เผยแพร่ และทบทวนตามรอบเวลาและเมื่อมีการเปลี่ยนแปลงสำคัญ',
    P, 'CIA', 'identify', 'governance'],
  ['5.2', 'Information security roles and responsibilities', 'บทบาทและความรับผิดชอบด้านความมั่นคงปลอดภัย',
    'Name who owns each security responsibility and make sure they know it.',
    'กำหนดว่าใครรับผิดชอบงานความมั่นคงปลอดภัยแต่ละด้าน และให้ผู้นั้นรับทราบ',
    P, 'CIA', 'identify', 'governance'],
  ['5.3', 'Segregation of duties', 'การแบ่งแยกหน้าที่',
    'Split conflicting duties so one person cannot both request and approve, or change and audit, the same thing.',
    'แยกหน้าที่ที่ขัดกันเพื่อไม่ให้คนเดียวทั้งขอและอนุมัติ หรือทั้งแก้ไขและตรวจสอบสิ่งเดียวกัน',
    P, 'CIA', 'protect', 'governance, identity_and_access_management'],
  ['5.4', 'Management responsibilities', 'ความรับผิดชอบของผู้บริหาร',
    'Managers must require staff to follow the security policy and procedures and hold them to it.',
    'ผู้บริหารต้องกำหนดให้พนักงานปฏิบัติตามนโยบายและขั้นตอนความมั่นคงปลอดภัย และติดตามให้เป็นไปตามนั้น',
    P, 'CIA', 'identify', 'governance'],
  ['5.5', 'Contact with authorities', 'การติดต่อกับหน่วยงานรัฐ',
    'Know which regulators, law enforcement and supervisory bodies to contact, and how, before you need them.',
    'รู้ว่าต้องติดต่อหน่วยงานกำกับดูแล ตำรวจ หรือหน่วยงานที่เกี่ยวข้องรายใด และอย่างไร ก่อนที่จะจำเป็นต้องใช้',
    P + ',' + C, 'CIA', 'identify,protect,respond,recover', 'governance'],
  ['5.6', 'Contact with special interest groups', 'การติดต่อกับกลุ่มผู้เชี่ยวชาญเฉพาะด้าน',
    'Stay connected to security communities, CERTs and vendor advisories so warnings reach you early.',
    'รักษาการติดต่อกับชุมชนความมั่นคงปลอดภัย CERT และคำแนะนำจากผู้ผลิต เพื่อให้ได้รับคำเตือนแต่เนิ่น ๆ',
    P + ',' + C, 'CIA', 'protect,respond,recover', 'governance'],
  ['5.7', 'Threat intelligence', 'ข่าวกรองภัยคุกคาม',
    'Collect and analyse information about threats and turn it into concrete actions and controls.',
    'รวบรวมและวิเคราะห์ข้อมูลภัยคุกคาม แล้วแปลงเป็นการดำเนินการและมาตรการที่เป็นรูปธรรม',
    P + ',' + D + ',' + C, 'CIA', 'identify,detect,respond', 'threat_and_vulnerability_management'],
  ['5.8', 'Information security in project management', 'ความมั่นคงปลอดภัยในการบริหารโครงการ',
    'Build security requirements and review points into every project, not only IT ones.',
    'ใส่ข้อกำหนดและจุดตรวจสอบด้านความมั่นคงปลอดภัยไว้ในทุกโครงการ ไม่เฉพาะโครงการไอที',
    P, 'CIA', 'identify,protect', 'governance'],
  ['5.9', 'Inventory of information and other associated assets', 'ทะเบียนสารสนเทศและทรัพย์สินที่เกี่ยวข้อง',
    'Keep an accurate inventory of information and the assets that hold it, each with an owner.',
    'จัดทำทะเบียนสารสนเทศและทรัพย์สินที่เก็บสารสนเทศให้ถูกต้อง โดยแต่ละรายการมีเจ้าของ',
    P, 'CIA', 'identify', 'asset_management'],
  ['5.10', 'Acceptable use of information and other associated assets', 'การใช้งานสารสนเทศและทรัพย์สินอย่างเหมาะสม',
    'Define and communicate the rules for handling information and equipment.',
    'กำหนดและสื่อสารกฎการใช้งานสารสนเทศและอุปกรณ์',
    P, 'CIA', 'protect', 'asset_management, information_protection'],
  ['5.11', 'Return of assets', 'การส่งคืนทรัพย์สิน',
    'Get every device, badge and document back when someone leaves or a contract ends.',
    'เรียกคืนอุปกรณ์ บัตร และเอกสารทั้งหมดเมื่อบุคคลพ้นสภาพหรือสัญญาสิ้นสุด',
    P, 'CIA', 'protect', 'asset_management'],
  ['5.12', 'Classification of information', 'การจัดชั้นความลับของสารสนเทศ',
    'Classify information by confidentiality, integrity, availability and legal needs so it is handled accordingly.',
    'จัดชั้นสารสนเทศตามความลับ ความถูกต้อง ความพร้อมใช้ และข้อกำหนดทางกฎหมาย เพื่อให้จัดการได้เหมาะสม',
    P, 'CIA', 'identify,protect', 'information_protection'],
  ['5.13', 'Labelling of information', 'การติดป้ายกำกับสารสนเทศ',
    'Label information according to its classification, in a way people and systems can act on.',
    'ติดป้ายกำกับสารสนเทศตามชั้นความลับ ในรูปแบบที่คนและระบบนำไปใช้ได้',
    P, 'CIA', 'protect', 'information_protection'],
  ['5.14', 'Information transfer', 'การถ่ายโอนสารสนเทศ',
    'Set rules and agreements for moving information by any channel, inside and outside the organisation.',
    'กำหนดกฎและข้อตกลงสำหรับการส่งสารสนเทศผ่านทุกช่องทาง ทั้งภายในและภายนอกองค์กร',
    P, 'CIA', 'protect', 'asset_management, information_protection'],
  ['5.15', 'Access control', 'การควบคุมการเข้าถึง',
    'Define who may access what, physically and logically, based on business need.',
    'กำหนดว่าใครเข้าถึงอะไรได้ ทั้งทางกายภาพและตรรกะ ตามความจำเป็นทางธุรกิจ',
    P, 'CIA', 'protect', 'identity_and_access_management'],
  ['5.16', 'Identity management', 'การบริหารจัดการอัตลักษณ์',
    'Manage the full lifecycle of identities for people and systems: create, change, disable, remove.',
    'บริหารวงจรชีวิตอัตลักษณ์ของบุคคลและระบบทั้งหมด: สร้าง เปลี่ยน ระงับ ลบ',
    P, 'CIA', 'protect', 'identity_and_access_management'],
  ['5.17', 'Authentication information', 'ข้อมูลสำหรับการพิสูจน์ตัวตน',
    'Control how passwords, keys and tokens are issued, stored and changed, and teach people to handle them.',
    'ควบคุมวิธีการออก จัดเก็บ และเปลี่ยนรหัสผ่าน กุญแจ และโทเคน และสอนผู้ใช้ให้ดูแลอย่างถูกต้อง',
    P, 'CIA', 'protect', 'identity_and_access_management'],
  ['5.18', 'Access rights', 'สิทธิ์การเข้าถึง',
    'Grant, review and revoke access rights following the access control policy.',
    'ให้ ทบทวน และเพิกถอนสิทธิ์การเข้าถึงตามนโยบายควบคุมการเข้าถึง',
    P, 'CIA', 'protect', 'identity_and_access_management'],
  ['5.19', 'Information security in supplier relationships', 'ความมั่นคงปลอดภัยในความสัมพันธ์กับผู้ส่งมอบ',
    'Manage the risks that come with suppliers having access to your information or systems.',
    'บริหารความเสี่ยงจากการที่ผู้ส่งมอบเข้าถึงสารสนเทศหรือระบบขององค์กร',
    P, 'CIA', 'identify', 'supplier_relationships_security'],
  ['5.20', 'Addressing information security within supplier agreements', 'ข้อกำหนดด้านความมั่นคงปลอดภัยในสัญญากับผู้ส่งมอบ',
    'Write the security requirements into supplier contracts.',
    'ระบุข้อกำหนดด้านความมั่นคงปลอดภัยไว้ในสัญญากับผู้ส่งมอบ',
    P, 'CIA', 'identify', 'supplier_relationships_security'],
  ['5.21', 'Managing information security in the ICT supply chain', 'การจัดการความมั่นคงปลอดภัยในห่วงโซ่อุปทาน ICT',
    'Manage security risks through the whole chain of hardware, software and service providers.',
    'บริหารความเสี่ยงตลอดห่วงโซ่ผู้ให้บริการฮาร์ดแวร์ ซอฟต์แวร์ และบริการ',
    P, 'CIA', 'identify', 'supplier_relationships_security'],
  ['5.22', 'Monitoring, review and change management of supplier services', 'การติดตาม ทบทวน และจัดการการเปลี่ยนแปลงบริการของผู้ส่งมอบ',
    'Keep watching supplier performance and security, and manage changes to their services.',
    'ติดตามผลการดำเนินงานและความมั่นคงปลอดภัยของผู้ส่งมอบอย่างต่อเนื่อง และจัดการการเปลี่ยนแปลงบริการ',
    P, 'CIA', 'identify', 'supplier_relationships_security, information_security_assurance'],
  ['5.23', 'Information security for use of cloud services', 'ความมั่นคงปลอดภัยในการใช้บริการคลาวด์',
    'Define how cloud services are selected, used, managed and exited, in line with security needs.',
    'กำหนดวิธีเลือก ใช้ บริหาร และยกเลิกบริการคลาวด์ให้สอดคล้องกับความต้องการด้านความมั่นคงปลอดภัย',
    P, 'CIA', 'protect', 'supplier_relationships_security'],
  ['5.24', 'Information security incident management planning and preparation', 'การวางแผนและเตรียมความพร้อมจัดการเหตุการณ์',
    'Have a defined process, roles and contacts ready before an incident happens.',
    'มีกระบวนการ บทบาท และผู้ติดต่อที่กำหนดไว้ก่อนเกิดเหตุการณ์',
    C, 'CIA', 'respond,recover', 'governance, information_security_event_management'],
  ['5.25', 'Assessment and decision on information security events', 'การประเมินและตัดสินใจเกี่ยวกับเหตุการณ์',
    'Triage events against defined criteria and decide which are incidents.',
    'คัดกรองเหตุการณ์ตามเกณฑ์ที่กำหนด และตัดสินใจว่ารายการใดเป็นอุบัติการณ์',
    D, 'CIA', 'detect,respond', 'information_security_event_management'],
  ['5.26', 'Response to information security incidents', 'การตอบสนองต่ออุบัติการณ์',
    'Respond to incidents following the documented procedures.',
    'ตอบสนองต่ออุบัติการณ์ตามขั้นตอนที่จัดทำเป็นเอกสาร',
    C, 'CIA', 'respond,recover', 'information_security_event_management'],
  ['5.27', 'Learning from information security incidents', 'การเรียนรู้จากอุบัติการณ์',
    'Use what incidents teach you to strengthen controls.',
    'นำบทเรียนจากอุบัติการณ์มาเสริมความแข็งแกร่งของมาตรการควบคุม',
    P, 'CIA', 'identify,protect', 'information_security_event_management'],
  ['5.28', 'Collection of evidence', 'การรวบรวมหลักฐาน',
    'Identify, collect and preserve evidence in a way that stands up later.',
    'ระบุ รวบรวม และรักษาหลักฐานในลักษณะที่ใช้อ้างอิงได้ในภายหลัง',
    C, 'CIA', 'detect,respond', 'information_security_event_management'],
  ['5.29', 'Information security during disruption', 'ความมั่นคงปลอดภัยระหว่างเหตุชะงัก',
    'Plan how security is kept at an appropriate level while operations are disrupted.',
    'วางแผนรักษาระดับความมั่นคงปลอดภัยที่เหมาะสมขณะการดำเนินงานหยุดชะงัก',
    P + ',' + C, 'CIA', 'protect,respond', 'continuity'],
  ['5.30', 'ICT readiness for business continuity', 'ความพร้อมของ ICT เพื่อความต่อเนื่องทางธุรกิจ',
    'Plan, implement and test the ICT capability needed to meet continuity objectives.',
    'วางแผน ดำเนินการ และทดสอบขีดความสามารถ ICT ที่จำเป็นต่อวัตถุประสงค์ความต่อเนื่อง',
    C, 'A', 'respond', 'continuity'],
  ['5.31', 'Legal, statutory, regulatory and contractual requirements', 'ข้อกำหนดทางกฎหมาย ข้อบังคับ และสัญญา',
    'Identify every legal, regulatory and contractual requirement that applies and keep the list current.',
    'ระบุข้อกำหนดทางกฎหมาย ข้อบังคับ และสัญญาทั้งหมดที่เกี่ยวข้อง และปรับให้เป็นปัจจุบันเสมอ',
    P, 'CIA', 'identify,protect', 'legal_and_compliance'],
  ['5.32', 'Intellectual property rights', 'สิทธิ์ในทรัพย์สินทางปัญญา',
    'Protect intellectual property rights, including software licensing.',
    'คุ้มครองสิทธิ์ในทรัพย์สินทางปัญญา รวมถึงการใช้สิทธิ์ซอฟต์แวร์',
    P, 'CIA', 'identify,protect', 'legal_and_compliance'],
  ['5.33', 'Protection of records', 'การคุ้มครองบันทึก',
    'Protect records from loss, destruction, falsification and unauthorised access.',
    'ปกป้องบันทึกจากการสูญหาย ทำลาย ปลอมแปลง และการเข้าถึงโดยไม่ได้รับอนุญาต',
    P, 'CIA', 'identify,protect', 'legal_and_compliance, asset_management, information_protection'],
  ['5.34', 'Privacy and protection of personal identifiable information (PII)', 'ความเป็นส่วนตัวและการคุ้มครองข้อมูลส่วนบุคคล',
    'Meet the legal and contractual requirements for handling personal data.',
    'ปฏิบัติตามข้อกำหนดทางกฎหมายและสัญญาในการจัดการข้อมูลส่วนบุคคล',
    P, 'CIA', 'identify,protect', 'information_protection, legal_and_compliance'],
  ['5.35', 'Independent review of information security', 'การทบทวนความมั่นคงปลอดภัยโดยอิสระ',
    'Have the security approach reviewed independently on a schedule and after major change.',
    'ให้มีการทบทวนแนวทางความมั่นคงปลอดภัยโดยผู้ที่เป็นอิสระตามรอบเวลาและเมื่อมีการเปลี่ยนแปลงสำคัญ',
    P + ',' + C, 'CIA', 'identify,protect', 'information_security_assurance'],
  ['5.36', 'Compliance with policies, rules and standards for information security', 'การปฏิบัติตามนโยบาย กฎ และมาตรฐาน',
    'Check regularly that people and systems follow the security policies and standards.',
    'ตรวจสอบอย่างสม่ำเสมอว่าบุคลากรและระบบปฏิบัติตามนโยบายและมาตรฐานความมั่นคงปลอดภัย',
    P, 'CIA', 'identify,protect', 'legal_and_compliance, information_security_assurance'],
  ['5.37', 'Documented operating procedures', 'ขั้นตอนปฏิบัติงานที่เป็นเอกสาร',
    'Document operating procedures for information processing and make them available to those who need them.',
    'จัดทำขั้นตอนปฏิบัติงานสำหรับการประมวลผลสารสนเทศเป็นเอกสาร และให้ผู้ที่ต้องใช้เข้าถึงได้',
    P + ',' + C, 'CIA', 'protect,recover', 'asset_management, physical_security, system_and_network_security, application_security, secure_configuration, identity_and_access_management, threat_and_vulnerability_management, continuity, information_security_event_management'],

  // ── 6 People ────────────────────────────────────────────────
  ['6.1', 'Screening', 'การตรวจสอบประวัติ',
    'Vet candidates before hiring, and again for sensitive roles, in proportion to the risk and the law.',
    'ตรวจสอบประวัติผู้สมัครก่อนจ้าง และตรวจซ้ำสำหรับตำแหน่งสำคัญ ตามระดับความเสี่ยงและกฎหมาย',
    P, 'CIA', 'protect', 'human_resource_security'],
  ['6.2', 'Terms and conditions of employment', 'ข้อกำหนดและเงื่อนไขการจ้างงาน',
    'Put security responsibilities into employment contracts.',
    'ระบุความรับผิดชอบด้านความมั่นคงปลอดภัยไว้ในสัญญาจ้าง',
    P, 'CIA', 'protect', 'human_resource_security'],
  ['6.3', 'Information security awareness, education and training', 'การสร้างความตระหนัก การให้ความรู้ และการฝึกอบรม',
    'Give everyone regular, role-appropriate security awareness and training.',
    'ให้ทุกคนได้รับการสร้างความตระหนักและฝึกอบรมด้านความมั่นคงปลอดภัยที่เหมาะกับบทบาทอย่างสม่ำเสมอ',
    P, 'CIA', 'protect', 'human_resource_security'],
  ['6.4', 'Disciplinary process', 'กระบวนการทางวินัย',
    'Have a formal, communicated process for handling policy violations.',
    'มีกระบวนการที่เป็นทางการและสื่อสารแล้วสำหรับจัดการการละเมิดนโยบาย',
    P + ',' + C, 'CIA', 'protect,respond', 'human_resource_security'],
  ['6.5', 'Responsibilities after termination or change of employment', 'ความรับผิดชอบหลังสิ้นสุดหรือเปลี่ยนแปลงการจ้างงาน',
    'Define which security duties continue after someone leaves or changes role, and enforce them.',
    'กำหนดหน้าที่ด้านความมั่นคงปลอดภัยที่ยังคงอยู่หลังบุคคลลาออกหรือเปลี่ยนตำแหน่ง และบังคับใช้',
    P, 'CIA', 'protect', 'human_resource_security, asset_management'],
  ['6.6', 'Confidentiality or non-disclosure agreements', 'ข้อตกลงรักษาความลับ',
    'Use signed confidentiality agreements that reflect what actually needs protecting, and review them.',
    'ใช้ข้อตกลงรักษาความลับที่ลงนามและสะท้อนสิ่งที่ต้องคุ้มครองจริง และทบทวนเป็นระยะ',
    P, 'C', 'protect', 'human_resource_security, information_protection, supplier_relationships_security'],
  ['6.7', 'Remote working', 'การทำงานระยะไกล',
    'Put security measures in place for people working outside the premises.',
    'จัดให้มีมาตรการความมั่นคงปลอดภัยสำหรับผู้ที่ทำงานนอกสถานที่',
    P, 'CIA', 'protect', 'asset_management, information_protection, physical_security, system_and_network_security'],
  ['6.8', 'Information security event reporting', 'การรายงานเหตุการณ์ความมั่นคงปลอดภัย',
    'Make it easy and expected for anyone to report a security event quickly.',
    'ทำให้ทุกคนรายงานเหตุการณ์ความมั่นคงปลอดภัยได้ง่ายและรวดเร็ว และถือเป็นสิ่งที่คาดหวัง',
    D, 'CIA', 'detect', 'information_security_event_management'],

  // ── 7 Physical ──────────────────────────────────────────────
  ['7.1', 'Physical security perimeters', 'ขอบเขตความมั่นคงปลอดภัยทางกายภาพ',
    'Define secure areas and protect their boundaries.',
    'กำหนดพื้นที่หวงห้ามและป้องกันขอบเขตของพื้นที่นั้น',
    P, 'CIA', 'protect', 'physical_security'],
  ['7.2', 'Physical entry', 'การเข้าออกทางกายภาพ',
    'Control who can enter secure areas, and log it.',
    'ควบคุมว่าใครเข้าพื้นที่หวงห้ามได้ และบันทึกไว้',
    P, 'CIA', 'protect', 'physical_security, identity_and_access_management'],
  ['7.3', 'Securing offices, rooms and facilities', 'การรักษาความปลอดภัยสำนักงาน ห้อง และสิ่งอำนวยความสะดวก',
    'Design and protect offices and rooms so sensitive work is not exposed.',
    'ออกแบบและป้องกันสำนักงานและห้องต่าง ๆ ไม่ให้งานที่อ่อนไหวถูกเปิดเผย',
    P, 'CIA', 'protect', 'physical_security, asset_management'],
  ['7.4', 'Physical security monitoring', 'การเฝ้าระวังความปลอดภัยทางกายภาพ',
    'Continuously monitor premises for unauthorised physical access.',
    'เฝ้าระวังสถานที่อย่างต่อเนื่องเพื่อตรวจจับการเข้าถึงทางกายภาพโดยไม่ได้รับอนุญาต',
    P + ',' + D, 'CIA', 'protect,detect', 'physical_security'],
  ['7.5', 'Protecting against physical and environmental threats', 'การป้องกันภัยคุกคามทางกายภาพและสิ่งแวดล้อม',
    'Protect against fire, flood, power loss and other environmental threats.',
    'ป้องกันอัคคีภัย น้ำท่วม ไฟฟ้าดับ และภัยคุกคามทางสิ่งแวดล้อมอื่น ๆ',
    P, 'CIA', 'protect', 'physical_security'],
  ['7.6', 'Working in secure areas', 'การทำงานในพื้นที่หวงห้าม',
    'Set rules for behaviour and equipment inside secure areas.',
    'กำหนดกฎเกี่ยวกับพฤติกรรมและอุปกรณ์ภายในพื้นที่หวงห้าม',
    P, 'CIA', 'protect', 'physical_security'],
  ['7.7', 'Clear desk and clear screen', 'โต๊ะสะอาดและหน้าจอสะอาด',
    'Keep papers and screens clear of sensitive information when unattended.',
    'ไม่ทิ้งเอกสารและหน้าจอที่มีข้อมูลอ่อนไหวไว้เมื่อไม่มีผู้ดูแล',
    P, 'C', 'protect', 'physical_security'],
  ['7.8', 'Equipment siting and protection', 'การจัดวางและป้องกันอุปกรณ์',
    'Place and protect equipment to reduce environmental and unauthorised-access risks.',
    'จัดวางและป้องกันอุปกรณ์เพื่อลดความเสี่ยงจากสิ่งแวดล้อมและการเข้าถึงโดยไม่ได้รับอนุญาต',
    P, 'CIA', 'protect', 'physical_security, asset_management'],
  ['7.9', 'Security of assets off-premises', 'ความปลอดภัยของทรัพย์สินนอกสถานที่',
    'Protect devices and information taken outside the premises.',
    'ปกป้องอุปกรณ์และสารสนเทศที่นำออกไปนอกสถานที่',
    P, 'CIA', 'protect', 'physical_security, asset_management'],
  ['7.10', 'Storage media', 'สื่อบันทึกข้อมูล',
    'Manage removable media through its whole life: acquisition, use, transport, disposal.',
    'จัดการสื่อบันทึกข้อมูลตลอดวงจร: จัดหา ใช้งาน ขนส่ง ทำลาย',
    P, 'CIA', 'protect', 'physical_security, asset_management'],
  ['7.11', 'Supporting utilities', 'ระบบสาธารณูปโภคสนับสนุน',
    'Protect facilities from failures in power, water, cooling and connectivity.',
    'ป้องกันสถานที่จากความล้มเหลวของไฟฟ้า น้ำ ระบบทำความเย็น และการเชื่อมต่อ',
    P + ',' + D, 'IA', 'protect,detect', 'physical_security'],
  ['7.12', 'Cabling security', 'ความปลอดภัยของสายเคเบิล',
    'Protect power and data cables from interception, interference and damage.',
    'ป้องกันสายไฟและสายสื่อสารจากการดักฟัง การรบกวน และความเสียหาย',
    P, 'CA', 'protect', 'physical_security'],
  ['7.13', 'Equipment maintenance', 'การบำรุงรักษาอุปกรณ์',
    'Maintain equipment correctly so it stays available and information stays protected.',
    'บำรุงรักษาอุปกรณ์อย่างถูกต้องเพื่อให้พร้อมใช้และสารสนเทศยังได้รับการปกป้อง',
    P, 'CIA', 'protect,recover', 'physical_security, asset_management'],
  ['7.14', 'Secure disposal or re-use of equipment', 'การทำลายหรือนำอุปกรณ์กลับมาใช้อย่างปลอดภัย',
    'Wipe or destroy data and licensed software before equipment is disposed of or reused.',
    'ลบหรือทำลายข้อมูลและซอฟต์แวร์ที่มีสิทธิ์ใช้ก่อนทิ้งหรือนำอุปกรณ์กลับมาใช้',
    P, 'C', 'protect', 'physical_security, asset_management'],

  // ── 8 Technological ─────────────────────────────────────────
  ['8.1', 'User endpoint devices', 'อุปกรณ์ปลายทางของผู้ใช้',
    'Protect information on laptops, phones and other user devices.',
    'ปกป้องสารสนเทศบนแล็ปท็อป โทรศัพท์ และอุปกรณ์ผู้ใช้อื่น ๆ',
    P, 'CIA', 'protect', 'asset_management, information_protection'],
  ['8.2', 'Privileged access rights', 'สิทธิ์การเข้าถึงระดับสูง',
    'Restrict and tightly manage administrative and other privileged access.',
    'จำกัดและบริหารสิทธิ์ผู้ดูแลระบบและสิทธิ์ระดับสูงอื่น ๆ อย่างเข้มงวด',
    P, 'CIA', 'protect', 'identity_and_access_management'],
  ['8.3', 'Information access restriction', 'การจำกัดการเข้าถึงสารสนเทศ',
    'Restrict access to information and assets according to the access policy.',
    'จำกัดการเข้าถึงสารสนเทศและทรัพย์สินตามนโยบายการเข้าถึง',
    P, 'CIA', 'protect', 'identity_and_access_management'],
  ['8.4', 'Access to source code', 'การเข้าถึงซอร์สโค้ด',
    'Control read and write access to source code, tools and libraries.',
    'ควบคุมสิทธิ์อ่านและเขียนซอร์สโค้ด เครื่องมือ และไลบรารี',
    P, 'CIA', 'protect', 'identity_and_access_management, application_security, secure_configuration'],
  ['8.5', 'Secure authentication', 'การพิสูจน์ตัวตนที่มั่นคงปลอดภัย',
    'Use authentication that matches the sensitivity of what is accessed, including multi-factor.',
    'ใช้การพิสูจน์ตัวตนที่เหมาะกับความอ่อนไหวของสิ่งที่เข้าถึง รวมถึงหลายปัจจัย',
    P, 'CIA', 'protect', 'identity_and_access_management'],
  ['8.6', 'Capacity management', 'การบริหารขีดความสามารถ',
    'Monitor and plan resource capacity so systems keep meeting demand.',
    'ติดตามและวางแผนขีดความสามารถของทรัพยากรเพื่อให้ระบบรองรับความต้องการได้ต่อเนื่อง',
    P + ',' + D, 'IA', 'identify,protect,detect', 'continuity'],
  ['8.7', 'Protection against malware', 'การป้องกันมัลแวร์',
    'Combine technical controls with user awareness to prevent, detect and recover from malware.',
    'ผสานมาตรการทางเทคนิคกับความตระหนักของผู้ใช้เพื่อป้องกัน ตรวจจับ และกู้คืนจากมัลแวร์',
    P + ',' + D + ',' + C, 'CIA', 'protect,detect', 'system_and_network_security, information_protection'],
  ['8.8', 'Management of technical vulnerabilities', 'การจัดการช่องโหว่ทางเทคนิค',
    'Find out about vulnerabilities in the systems you use, assess exposure, and fix them in time.',
    'ติดตามช่องโหว่ในระบบที่ใช้ ประเมินความเสี่ยง และแก้ไขให้ทันเวลา',
    P, 'CIA', 'identify,protect', 'threat_and_vulnerability_management'],
  ['8.9', 'Configuration management', 'การบริหารการตั้งค่า',
    'Define, apply, monitor and review secure configurations for hardware, software and networks.',
    'กำหนด ใช้ ติดตาม และทบทวนการตั้งค่าที่มั่นคงปลอดภัยสำหรับฮาร์ดแวร์ ซอฟต์แวร์ และเครือข่าย',
    P, 'CIA', 'protect', 'secure_configuration'],
  ['8.10', 'Information deletion', 'การลบสารสนเทศ',
    'Delete information when it is no longer needed, from all the places it lives.',
    'ลบสารสนเทศเมื่อไม่จำเป็นต้องใช้แล้ว จากทุกที่ที่มีอยู่',
    P, 'C', 'protect', 'information_protection, legal_and_compliance'],
  ['8.11', 'Data masking', 'การปกปิดข้อมูล',
    'Mask, anonymise or pseudonymise data where policy and law require it.',
    'ปกปิด ทำให้ไม่ระบุตัวตน หรือใช้นามแฝงกับข้อมูลตามที่นโยบายและกฎหมายกำหนด',
    P, 'C', 'protect', 'information_protection'],
  ['8.12', 'Data leakage prevention', 'การป้องกันข้อมูลรั่วไหล',
    'Apply measures to systems and channels that carry sensitive information to stop it leaking.',
    'ใช้มาตรการกับระบบและช่องทางที่มีข้อมูลอ่อนไหวเพื่อป้องกันการรั่วไหล',
    P + ',' + D, 'C', 'protect,detect', 'information_protection'],
  ['8.13', 'Information backup', 'การสำรองข้อมูล',
    'Back up information, software and systems, and test that restores actually work.',
    'สำรองสารสนเทศ ซอฟต์แวร์ และระบบ และทดสอบว่ากู้คืนได้จริง',
    C, 'IA', 'recover', 'continuity'],
  ['8.14', 'Redundancy of information processing facilities', 'ความซ้ำซ้อนของสิ่งอำนวยความสะดวกประมวลผล',
    'Build in enough redundancy to meet availability requirements.',
    'จัดให้มีความซ้ำซ้อนเพียงพอเพื่อตอบสนองข้อกำหนดด้านความพร้อมใช้',
    P, 'A', 'protect', 'continuity, asset_management'],
  ['8.15', 'Logging', 'การบันทึกล็อก',
    'Produce, protect and analyse logs of activity, exceptions and security events.',
    'สร้าง ปกป้อง และวิเคราะห์ล็อกกิจกรรม ข้อผิดพลาด และเหตุการณ์ความมั่นคงปลอดภัย',
    D, 'CIA', 'detect', 'information_security_event_management'],
  ['8.16', 'Monitoring activities', 'การเฝ้าติดตามกิจกรรม',
    'Monitor networks, systems and applications for anomalies and act on what you find.',
    'เฝ้าติดตามเครือข่าย ระบบ และแอปพลิเคชันเพื่อหาความผิดปกติ และดำเนินการกับสิ่งที่พบ',
    D + ',' + C, 'CIA', 'detect,respond', 'information_security_event_management'],
  ['8.17', 'Clock synchronization', 'การซิงโครไนซ์นาฬิกา',
    'Synchronise system clocks to an approved time source so logs line up.',
    'ซิงโครไนซ์นาฬิกาของระบบกับแหล่งเวลาที่อนุมัติเพื่อให้ล็อกสอดคล้องกัน',
    D, 'I', 'protect,detect', 'information_security_event_management'],
  ['8.18', 'Use of privileged utility programs', 'การใช้โปรแกรมอรรถประโยชน์ระดับสูง',
    'Restrict and control tools that can override system and application controls.',
    'จำกัดและควบคุมเครื่องมือที่สามารถข้ามการควบคุมของระบบและแอปพลิเคชันได้',
    P, 'CIA', 'protect', 'system_and_network_security, secure_configuration, application_security'],
  ['8.19', 'Installation of software on operational systems', 'การติดตั้งซอฟต์แวร์บนระบบปฏิบัติการจริง',
    'Control how software gets installed on production systems.',
    'ควบคุมวิธีติดตั้งซอฟต์แวร์บนระบบที่ใช้งานจริง',
    P, 'CIA', 'protect', 'secure_configuration, application_security'],
  ['8.20', 'Networks security', 'ความมั่นคงปลอดภัยของเครือข่าย',
    'Secure, manage and control networks and network devices.',
    'รักษาความปลอดภัย บริหาร และควบคุมเครือข่ายและอุปกรณ์เครือข่าย',
    P + ',' + D, 'CIA', 'protect,detect', 'system_and_network_security'],
  ['8.21', 'Security of network services', 'ความมั่นคงปลอดภัยของบริการเครือข่าย',
    'Define and monitor the security level expected from each network service.',
    'กำหนดและติดตามระดับความมั่นคงปลอดภัยที่คาดหวังจากแต่ละบริการเครือข่าย',
    P + ',' + D, 'CIA', 'protect,detect', 'system_and_network_security'],
  ['8.22', 'Segregation of networks', 'การแบ่งแยกเครือข่าย',
    'Segment the network by service, user and system groups.',
    'แบ่งเครือข่ายตามกลุ่มบริการ ผู้ใช้ และระบบ',
    P, 'CIA', 'protect', 'system_and_network_security'],
  ['8.23', 'Web filtering', 'การกรองเว็บ',
    'Manage access to external websites to reduce exposure to malicious content.',
    'จัดการการเข้าถึงเว็บไซต์ภายนอกเพื่อลดการสัมผัสเนื้อหาที่เป็นอันตราย',
    P, 'CIA', 'protect', 'system_and_network_security'],
  ['8.24', 'Use of cryptography', 'การใช้การเข้ารหัสลับ',
    'Define rules for effective use of cryptography, including key management.',
    'กำหนดกฎการใช้การเข้ารหัสลับอย่างมีประสิทธิผล รวมถึงการบริหารกุญแจ',
    P, 'CIA', 'protect', 'secure_configuration'],
  ['8.25', 'Secure development life cycle', 'วงจรการพัฒนาที่มั่นคงปลอดภัย',
    'Set rules for building software and systems securely from the start.',
    'กำหนดกฎในการสร้างซอฟต์แวร์และระบบอย่างมั่นคงปลอดภัยตั้งแต่ต้น',
    P, 'CIA', 'protect', 'application_security, system_and_network_security'],
  ['8.26', 'Application security requirements', 'ข้อกำหนดความมั่นคงปลอดภัยของแอปพลิเคชัน',
    'Identify and specify security requirements when applications are built or bought.',
    'ระบุและกำหนดข้อกำหนดด้านความมั่นคงปลอดภัยเมื่อสร้างหรือจัดซื้อแอปพลิเคชัน',
    P, 'CIA', 'protect', 'application_security, system_and_network_security'],
  ['8.27', 'Secure system architecture and engineering principles', 'หลักการสถาปัตยกรรมและวิศวกรรมระบบที่มั่นคงปลอดภัย',
    'Establish secure engineering principles and apply them to every system development.',
    'กำหนดหลักวิศวกรรมที่มั่นคงปลอดภัยและนำไปใช้กับการพัฒนาระบบทุกรายการ',
    P, 'CIA', 'protect', 'application_security, system_and_network_security'],
  ['8.28', 'Secure coding', 'การเขียนโค้ดที่มั่นคงปลอดภัย',
    'Apply secure coding principles and tooling to software development.',
    'ใช้หลักการและเครื่องมือเขียนโค้ดที่มั่นคงปลอดภัยในการพัฒนาซอฟต์แวร์',
    P, 'CIA', 'protect', 'application_security, system_and_network_security'],
  ['8.29', 'Security testing in development and acceptance', 'การทดสอบความมั่นคงปลอดภัยระหว่างพัฒนาและยอมรับ',
    'Define and run security tests throughout development and before acceptance.',
    'กำหนดและดำเนินการทดสอบความมั่นคงปลอดภัยตลอดการพัฒนาและก่อนการยอมรับ',
    P, 'CIA', 'identify,protect', 'application_security, information_security_assurance, system_and_network_security'],
  ['8.30', 'Outsourced development', 'การพัฒนาโดยผู้รับจ้างภายนอก',
    'Direct, monitor and review development that is outsourced.',
    'กำกับ ติดตาม และทบทวนงานพัฒนาที่จ้างภายนอก',
    P + ',' + D, 'CIA', 'identify,protect,detect', 'system_and_network_security, application_security, supplier_relationships_security'],
  ['8.31', 'Separation of development, test and production environments', 'การแยกสภาพแวดล้อมพัฒนา ทดสอบ และใช้งานจริง',
    'Keep development, test and production environments separate and secured.',
    'แยกสภาพแวดล้อมพัฒนา ทดสอบ และใช้งานจริงออกจากกันและรักษาความปลอดภัย',
    P, 'CIA', 'protect', 'application_security, system_and_network_security'],
  ['8.32', 'Change management', 'การบริหารการเปลี่ยนแปลง',
    'Put changes to systems and facilities through a defined change process.',
    'นำการเปลี่ยนแปลงระบบและสิ่งอำนวยความสะดวกผ่านกระบวนการเปลี่ยนแปลงที่กำหนด',
    P, 'CIA', 'protect', 'application_security, system_and_network_security'],
  ['8.33', 'Test information', 'ข้อมูลสำหรับทดสอบ',
    'Select, protect and manage the data used for testing.',
    'คัดเลือก ปกป้อง และบริหารข้อมูลที่ใช้ในการทดสอบ',
    P, 'CI', 'protect', 'information_protection'],
  ['8.34', 'Protection of information systems during audit testing', 'การป้องกันระบบระหว่างการทดสอบตรวจสอบ',
    'Plan audit tests with management so they do not disrupt operations or expose data.',
    'วางแผนการทดสอบเพื่อตรวจสอบร่วมกับผู้บริหารเพื่อไม่ให้กระทบการดำเนินงานหรือเปิดเผยข้อมูล',
    P, 'CIA', 'protect', 'system_and_network_security, information_protection'],
];

function themeOf(id: string): Theme {
  const n = id.split('.')[0];
  return n === '5' ? 'organisational' : n === '6' ? 'people' : n === '7' ? 'physical' : 'technological';
}

export const ISO27001_CONTROLS: Control[] = rows.map(([id, en, th, sen, sth, types, cia, concepts, domains]) => ({
  id,
  theme: themeOf(id),
  title: { en, th },
  summary: { en: sen, th: sth },
  type: types.split(',').map((s) => s.trim()) as ControlType[],
  cia: cia.split('') as Cia[],
  concept: concepts.split(',').map((s) => s.trim()) as Concept[],
  domains: domains.split(',').map((s) => s.trim()),
}));

export const CONTROL_BY_ID: Record<string, Control> = Object.fromEntries(ISO27001_CONTROLS.map((c) => [c.id, c]));

/** Sort helper: numeric by clause then control number ("5.9" before "5.10"). */
export function compareControlId(a: string, b: string): number {
  const [a1, a2] = a.split('.').map(Number);
  const [b1, b2] = b.split('.').map(Number);
  return a1 - b1 || a2 - b2;
}
